# Generated by Django 4.1.4 on 2022-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_id_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
