# Generated by Django 4.1.4 on 2022-12-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_lot_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='winner',
            field=models.CharField(max_length=100),
        ),
    ]
